version: "3.9" 
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RaahilHayan
      POSTGRES_DB: visionai
    volumes:
      - visionai_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d visionai" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:RaahilHayan@db:5432/visionai
      SECRET_KEY: cd035af24639d41d202fd53f32a81eca0879b96ffff3816300d4b5ac46f25d96
      ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
      BACKEND_CORS_ORIGINS: '["http://localhost:3001"]'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3001"

volumes:
  visionai_pgdata:
