"""Add AI fields

Revision ID: 3c4b0974a4be
Revises: 9fd0c67be4c0
Create Date: 2026-08-30 13:30:55.175031

"""
from alembic import op
import sqlalchemy as sa


revision = '3c4b0974a4be'
down_revision = '9fd0c67be4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vision_test_sessions', sa.Column('symptoms', sa.JSON(), nullable=True))
    op.add_column('vision_test_sessions', sa.Column('ai_recommendation', sa.String(), nullable=True))
    op.add_column('vision_test_sessions', sa.Column('ai_explanation', sa.String(), nullable=True))
    op.add_column('vision_test_sessions', sa.Column('ai_factors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vision_test_sessions', 'ai_factors')
    op.drop_column('vision_test_sessions', 'ai_explanation')
    op.drop_column('vision_test_sessions', 'ai_recommendation')
    op.drop_column('vision_test_sessions', 'symptoms')
    # ### end Alembic commands ###
