"""Add test_type to session

Revision ID: 838075cef39d
Revises: 3c4b0974a4be
Create Date: 2026-08-30 19:16:01.535198

"""
from alembic import op
import sqlalchemy as sa


revision = '838075cef39d'
down_revision = '3c4b0974a4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vision_test_sessions', sa.Column('test_type', sa.Enum('acuity', 'color', 'astigmatism', 'contrast', name='testtype'), server_default='acuity', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vision_test_sessions', 'test_type')
    # ### end Alembic commands ###
