"""initial schema

Revision ID: 9fd0c67be4c0
Revises: 
Create Date: 2026-08-16 15:16:36.902732

"""
from alembic import op
import sqlalchemy as sa


revision = '9fd0c67be4c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='userrole'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vision_test_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'aborted_unreliable', name='teststatus'), nullable=True),
    sa.Column('test_distance_cm', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('reliability_flags', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'claimed', 'reviewed', name='consultationstatus'), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['vision_test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision_test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('eye', sa.Enum('left', 'right', 'both', name='eyeside'), nullable=False),
    sa.Column('acuity_score', sa.String(), nullable=True),
    sa.Column('smallest_line_read', sa.Integer(), nullable=True),
    sa.Column('correct_responses', sa.Integer(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('preliminary_flag', sa.String(), nullable=True),
    sa.Column('raw_responses', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['vision_test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vision_test_results')
    op.drop_table('consultations')
    op.drop_table('vision_test_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
